**Important: This notebook will only work with fastai-0.7.x. Do not try to run any fastai-1.x code from this path in the repository because it will load fastai-0.7.x**

In [ ]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

from fastai.imports import *
from fastai.torch_imports import *
from fastai.core import *
from fastai.model import fit
from fastai.dataset import *

import torchtext
from torchtext import vocab, data
from torchtext.datasets import language_modeling

from fastai.rnn_reg import *
from fastai.rnn_train import *
from fastai.nlp import *
from fastai.lm_rnn import *

## Language modeling

### Data

In [ ]:
PATH='data/wikitext-2/'
%ls {PATH}

models/  tmp/  wiki.test.tokens  wiki.train.tokens  wiki.valid.tokens


In [ ]:
!head -5 {PATH}wiki.train.tokens

 
 = Valkyria Chronicles III = 
 
 Senjō no Valkyria 3 : <unk> Chronicles ( Japanese : 戦場のヴァルキュリア3 , lit . Valkyria of the Battlefield 3 ) , commonly referred to as Valkyria Chronicles III outside Japan , is a tactical role @-@ playing video game developed by Sega and Media.Vision for the PlayStation Portable . Released in January 2011 in Japan , it is the third game in the Valkyria series . <unk> the same fusion of tactical and real @-@ time gameplay as its predecessors , the story runs parallel to the first game and follows the " Nameless " , a penal military unit serving the nation of Gallia during the Second Europan War who perform secret black operations and are pitted against the Imperial unit " <unk> Raven " . 
 The game began development in 2010 , carrying over a large portion of the work done on Valkyria Chronicles II . While it retained the standard features of the series , it also underwent multiple adjustments , such as making the game more <unk> for series newcomers . Char

In [ ]:
!wc -lwc {PATH}wiki.train.tokens

   36718  2051910 10797148 data/wikitext-2/wiki.train.tokens


In [ ]:
!wc -lwc {PATH}wiki.valid.tokens

   3760  213886 1121681 data/wikitext-2/wiki.valid.tokens


In [ ]:
TEXT = data.Field(lower=True)
FILES = dict(train='wiki.train.tokens', validation='wiki.valid.tokens', test='wiki.test.tokens')
bs,bptt = 80,70
md = LanguageModelData(PATH, TEXT, **FILES, bs=bs, bptt=bptt, min_freq=10)
len(md.trn_dl), md.nt, len(md.trn_ds), len(md.trn_ds[0].text)

(371, 12981, 1, 2088628)

In [ ]:
#md.trn_ds[0].text[:12], next(iter(md.trn_dl))

### Train

In [ ]:
em_sz = 200
nh = 500
nl = 3
learner = md.get_model(SGD_Momentum(0.7), bs, em_sz, nh, nl)
reg_fn=partial(seq2seq_reg, alpha=2, beta=1)

In [ ]:
clip=0.3
learner.fit(10, 1, wds=1e-6, reg_fn=reg_fn, clip=clip)

A Jupyter Widget

[ 0.      5.8902  5.5658]                                   



In [ ]:
learner.fit(10, 6, wds=1e-6, reg_fn=reg_fn, cycle_len=1, cycle_mult=2, clip=clip)

A Jupyter Widget

[ 0.      5.5214  5.3178]                                   
[ 1.      5.36    5.1435]                                   
[ 2.      5.2619  5.0643]                                   
[ 3.      5.166   4.9541]                                   
[ 4.      5.0275  4.8416]                                   
[ 5.      4.9453  4.7837]                                   
[ 6.      4.9306  4.7692]                                   
[ 7.      4.9195  4.7462]                                   
[ 8.      4.8391  4.6762]                                   
[ 9.      4.767   4.6317]                                   
[ 10.       4.718    4.5859]                                
[ 11.       4.6623   4.5497]                                
[ 12.       4.6262   4.5275]                                
[ 13.       4.6103   4.5196]                                
[ 14.       4.6206   4.5137]                                
[ 15.       4.6716   4.5614]                                
[ 16.       4.6237   4.5

In [ ]:
learner.save('lm_420')

In [ ]:
learner.fit(10, 6, wds=1e-6, reg_fn=reg_fn, cycle_len=1, cycle_mult=2, clip=clip)

A Jupyter Widget

[ 0.      4.2051  4.242 ]                                   
[ 1.      4.2466  4.2633]                                   
[ 2.      4.2073  4.2377]                                   
[ 3.      4.2657  4.2765]                                   
[ 4.      4.2209  4.2627]                                   
[ 5.      4.1965  4.2458]                                   
[ 6.      4.1746  4.2335]                                   
[ 7.      4.2657  4.2897]                                   
[ 8.      4.2401  4.277 ]                                   
[ 9.      4.2266  4.269 ]                                   
[ 10.       4.189    4.2546]                                
[ 11.       4.1639   4.2369]                                
[ 12.       4.1531   4.2288]                                
[ 13.       4.1233   4.2223]                                
[ 14.       4.1328   4.2161]                                
[ 15.       4.2515   4.2909]                                
[ 16.       4.2246   4.2

In [ ]:
learner.save('lm_419')

In [ ]:
learner.fit(10, 6, wds=1e-6, reg_fn=reg_fn, cycle_len=1, cycle_mult=2, clip=clip)

A Jupyter Widget

[ 0.      4.0781  4.2001]                                   
[ 1.      4.1227  4.2212]                                   
[ 2.      4.1012  4.1981]                                   
[ 3.      4.1524  4.243 ]                                   
[ 4.      4.1137  4.2235]                                   
[ 5.      4.0761  4.1977]                                   
[ 6.      4.072   4.1966]                                   
[ 7.      4.1489  4.2491]                                   
[ 8.      4.1355  4.2431]                                   
[ 9.      4.1167  4.2323]                                   
[ 10.       4.0797   4.2189]                                
[ 11.       4.048    4.2054]                                
[ 12.       4.0284   4.2013]                                
[ 13.       4.0436   4.1854]                                
[ 14.       4.0416   4.1864]                                
[ 15.       4.131    4.2443]                                
[ 16.       4.1205   4.2

In [ ]:
learner.save('lm_418')

In [ ]:
math.exp(4.17)

64.71545210740304

### Test

In [ ]:
m=learner.model
s=[""". <eos> The game began development in 2010 , carrying over a large portion of the work 
done on Valkyria Chronicles II . While it retained the standard features of """.split()]
t=TEXT.numericalize(s)

m[0].bs=1
m.reset(False)
res,*_ = m(t)

In [ ]:
nexts = torch.topk(res[-1], 10)[1]
[TEXT.vocab.itos[o] for o in to_np(nexts)]

['the', '<unk>', 'a', '"', 'an', 'its', 'this', 'their', 'all', 'other']

In [ ]:
for i in range(20):
    n=res[-1].topk(2)[1]
    n = n[1] if n.data[0]==0 else n[0]
    print(TEXT.vocab.itos[n.data[0]], end=' ')
    res,*_ = m(n[0].unsqueeze(0))

the film , and the first of the two @-@ year @-@ old , the " black " , a 

### End