## Basic core

This module contains all the basic functions we need in other modules of the fastai library (split with [`torch_core`](/torch_core.html#torch_core) that contains the ones requiring pytorch). Its documentation can easily be skipped at a first read, unless you want to know what a given function does.

In [ ]:
from fastai.gen_doc.nbdoc import *
from fastai.core import * 

## Global constants

`default_cpus = min(16, num_cpus())` <div style="text-align: right"><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L45">[source]</a></div>

## Check functions

In [ ]:
show_doc(has_arg)

<h4 id="has_arg" class="doc_header"><code>has_arg</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L283" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#has_arg-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>has_arg</code>(**`func`**, **`arg`**) → `bool`

<div class="collapse" id="has_arg-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#has_arg-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>has_arg</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

Check if `func` accepts `arg`.  

Examples for two [`fastai.core`](/core.html#core) functions.  Docstring shown before calling [`has_arg`](/core.html#has_arg) for reference


In [ ]:
has_arg(download_url,'url')

True

In [ ]:
has_arg(index_row,'x')

False

In [ ]:
has_arg(index_row,'a')

True

In [ ]:
show_doc(ifnone)

<h4 id="ifnone" class="doc_header"><code>ifnone</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L92" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#ifnone-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>ifnone</code>(**`a`**:`Any`, **`b`**:`Any`) → `Any`

<div class="collapse" id="ifnone-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#ifnone-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>ifnone</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_ifnone</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L39" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

`a` if `a` is not None, otherwise `b`.  

In [ ]:
param,alt_param = None,5
ifnone(param,alt_param)

5

In [ ]:
param,alt_param = None,[1,2,3]
ifnone(param,alt_param)

[1, 2, 3]

In [ ]:
show_doc(is1d)

<h4 id="is1d" class="doc_header"><code>is1d</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L96" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#is1d-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>is1d</code>(**`a`**:`Collection`\[`T_co`\]) → `bool`

<div class="collapse" id="is1d-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#is1d-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>is1d</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_is1d</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L235" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Return `True` if `a` is one-dimensional  

In [ ]:
two_d_array = np.arange(12).reshape(6,2)
print( two_d_array )
print( is1d(two_d_array) )

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
False


In [ ]:
is1d(two_d_array.flatten())

True

In [ ]:
show_doc(is_listy)

<h4 id="is_listy" class="doc_header"><code>is_listy</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L51" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#is_listy-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>is_listy</code>(**`x`**:`Any`) → `bool`

<div class="collapse" id="is_listy-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#is_listy-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>is_listy</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_listy</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L59" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Check if `x` is a `Collection`. `Tuple` or `List` qualify

In [ ]:
some_data = [1,2,3]
is_listy(some_data)

True

In [ ]:
some_data = (1,2,3)
is_listy(some_data)

True

In [ ]:
some_data = 1024
print( is_listy(some_data) )

False


In [ ]:
print( is_listy( [some_data] ) )

True


In [ ]:
some_data = dict([('a',1),('b',2),('c',3)])
print( some_data )
print( some_data.keys() )

{'a': 1, 'b': 2, 'c': 3}
dict_keys(['a', 'b', 'c'])


In [ ]:
print( is_listy(some_data) )
print( is_listy(some_data.keys()) )

False
False


In [ ]:
print( is_listy(list(some_data.keys())) )

True


In [ ]:
show_doc(is_tuple)

<h4 id="is_tuple" class="doc_header"><code>is_tuple</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L52" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#is_tuple-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>is_tuple</code>(**`x`**:`Any`) → `bool`

<div class="collapse" id="is_tuple-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#is_tuple-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>is_tuple</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_tuple</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L70" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Check if `x` is a `tuple`.

In [ ]:
print( is_tuple( [1,2,3] ) )

False


In [ ]:
print( is_tuple( (1,2,3) ) )

True


## Collection related functions

In [ ]:
show_doc(arange_of)

<h4 id="arange_of" class="doc_header"><code>arange_of</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L232" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#arange_of-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>arange_of</code>(**`x`**)

<div class="collapse" id="arange_of-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#arange_of-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>arange_of</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

Same as [`range_of`](/core.html#range_of) but returns an array.  

In [ ]:
arange_of([5,6,7])

array([0, 1, 2])

In [ ]:
type(arange_of([5,6,7]))

numpy.ndarray

In [ ]:
show_doc(array)

<h4 id="array" class="doc_header"><code>array</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L293" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#array-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>array</code>(**`a`**, **`dtype`**:`type`=***`None`***, **\*\*`kwargs`**) → `ndarray`

<div class="collapse" id="array-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#array-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>array</code>:</p><p>Some other tests where <code>array</code> is used:</p><ul><li><code>pytest -sv tests/test_core.py::test_arrays_split</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L141" class="source_link" style="float:right">[source]</a></li><li><code>pytest -sv tests/test_core.py::test_even_mults</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L178" class="source_link" style="float:right">[source]</a></li><li><code>pytest -sv tests/test_core.py::test_idx_dict</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L125" class="source_link" style="float:right">[source]</a></li><li><code>pytest -sv tests/test_core.py::test_is1d</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L235" class="source_link" style="float:right">[source]</a></li><li><code>pytest -sv tests/test_core.py::test_itembase_eq</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L242" class="source_link" style="float:right">[source]</a></li><li><code>pytest -sv tests/test_core.py::test_itembase_hash</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L304" class="source_link" style="float:right">[source]</a></li><li><code>pytest -sv tests/test_core.py::test_one_hot</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L218" class="source_link" style="float:right">[source]</a></li><li><code>pytest -sv tests/test_torch_core.py::test_model_type</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_torch_core.py#L227" class="source_link" style="float:right">[source]</a></li><li><code>pytest -sv tests/test_torch_core.py::test_tensor_array_monkey_patch</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_torch_core.py#L260" class="source_link" style="float:right">[source]</a></li><li><code>pytest -sv tests/test_torch_core.py::test_tensor_with_ndarray</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_torch_core.py#L18" class="source_link" style="float:right">[source]</a></li><li><code>pytest -sv tests/test_torch_core.py::test_to_detach</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_torch_core.py#L131" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Same as `np.array` but also handles generators. `kwargs` are passed to `np.array` with `dtype`.  

In [ ]:
array([1,2,3])

array([1, 2, 3])

Note that after we call the generator, we do not reset.  So the [`array`](/core.html#array) call has 5 less entries than it would if we ran from the start of the generator.

In [ ]:
def data_gen():
    i = 100.01
    while i<200:
        yield i
        i += 1.

ex_data_gen = data_gen()
for _ in range(5):
    print(next(ex_data_gen))

100.01
101.01
102.01
103.01
104.01


In [ ]:
array(ex_data_gen)

array([105.01, 106.01, 107.01, 108.01, ..., 196.01, 197.01, 198.01, 199.01])

In [ ]:
ex_data_gen_int = data_gen()

array(ex_data_gen_int,dtype=int)  #Cast output to int array

array([100, 101, 102, 103, ..., 196, 197, 198, 199])

In [ ]:
show_doc(arrays_split)

<h4 id="arrays_split" class="doc_header"><code>arrays_split</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L117" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#arrays_split-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>arrays_split</code>(**`mask`**:`ndarray`, **\*`arrs`**:`NPArrayableList`) → `SplitArrayList`

<div class="collapse" id="arrays_split-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#arrays_split-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>arrays_split</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_arrays_split</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L141" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Given `arrs` is [a,b,...] and `mask`index - return[(a[mask],a[~mask]),(b[mask],b[~mask]),...].  

In [ ]:
data_a = np.arange(15)
data_b = np.arange(15)[::-1]

mask_a = (data_a > 10)
print(data_a)
print(data_b)
print(mask_a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[False False False False False False False False False False False  True  True  True  True]


In [ ]:
arrays_split(mask_a,data_a)

[(array([11, 12, 13, 14]),),
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),)]

In [ ]:
np.vstack([data_a,data_b]).transpose().shape

(15, 2)

In [ ]:
arrays_split(mask_a,np.vstack([data_a,data_b]).transpose()) #must match on dimension 0

[(array([[11,  3],
         [12,  2],
         [13,  1],
         [14,  0]]),), (array([[ 0, 14],
         [ 1, 13],
         [ 2, 12],
         [ 3, 11],
         [ 4, 10],
         [ 5,  9],
         [ 6,  8],
         [ 7,  7],
         [ 8,  6],
         [ 9,  5],
         [10,  4]]),)]

In [ ]:
show_doc(chunks)

<h4 id="chunks" class="doc_header"><code>chunks</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L73" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#chunks-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>chunks</code>(**`l`**:`Collection`\[`T_co`\], **`n`**:`int`) → `Iterable`

<div class="collapse" id="chunks-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#chunks-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>chunks</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_chunks</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L46" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Yield successive `n`-sized chunks from `l`.  

You can transform a `Collection` into an `Iterable` of 'n' sized chunks by calling [`chunks`](/core.html#chunks):

In [ ]:
data = [0,1,2,3,4,5,6,7,8,9]
for chunk in chunks(data, 2):
    print(chunk)

[0, 1]
[2, 3]
[4, 5]
[6, 7]
[8, 9]


In [ ]:
for chunk in chunks(data, 3):
    print(chunk)

[0, 1, 2]
[3, 4, 5]
[6, 7, 8]
[9]


In [ ]:
show_doc(df_names_to_idx)

<h4 id="df_names_to_idx" class="doc_header"><code>df_names_to_idx</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L257" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#df_names_to_idx-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>df_names_to_idx</code>(**`names`**:`IntsOrStrs`, **`df`**:`DataFrame`)

<div class="collapse" id="df_names_to_idx-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#df_names_to_idx-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>df_names_to_idx</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_df_names_to_idx</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L213" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Return the column indexes of `names` in `df`.  

In [ ]:
ex_df = pd.DataFrame.from_dict({"a":[1,1,1],"b":[2,2,2]})
print(ex_df)

   a  b
0  1  2
1  1  2
2  1  2


In [ ]:
df_names_to_idx('b',ex_df)

[1]

In [ ]:
show_doc(extract_kwargs)

<h4 id="extract_kwargs" class="doc_header"><code>extract_kwargs</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L156" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#extract_kwargs-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>extract_kwargs</code>(**`names`**:`StrList`, **`kwargs`**:`KWArgs`)

<div class="collapse" id="extract_kwargs-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#extract_kwargs-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>extract_kwargs</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

Extract the keys in `names` from the `kwargs`.  

In [ ]:
key_word_args = {"a":2,"some_list":[1,2,3],"param":'mean'}
key_word_args

{'a': 2, 'some_list': [1, 2, 3], 'param': 'mean'}

In [ ]:
(extracted_val,remainder) = extract_kwargs(['param'],key_word_args)
print( extracted_val,remainder )

{'param': 'mean'} {'a': 2, 'some_list': [1, 2, 3]}


In [ ]:
show_doc(idx_dict)

<h4 id="idx_dict" class="doc_header"><code>idx_dict</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L106" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#idx_dict-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>idx_dict</code>(**`a`**)

<div class="collapse" id="idx_dict-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#idx_dict-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>idx_dict</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_idx_dict</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L125" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Create a dictionary value to index from `a`.  

In [ ]:
idx_dict(['a','b','c'])

{'a': 0, 'b': 1, 'c': 2}

In [ ]:
show_doc(index_row)

<h4 id="index_row" class="doc_header"><code>index_row</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L269" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#index_row-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>index_row</code>(**`a`**:`Union`\[`Collection`\[`T_co`\], `DataFrame`, `Series`\], **`idxs`**:`Collection`\[`int`\]) → `Any`

<div class="collapse" id="index_row-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#index_row-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>index_row</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

Return the slice of `a` corresponding to `idxs`.  

`a` is basically something you can index into like a dataframe, an array or a list.

In [ ]:
data = [0,1,2,3,4,5,6,7,8,9]
index_row(data,4)

4

In [ ]:
index_row(pd.Series(data),7)

7

In [ ]:
data_df = pd.DataFrame([data[::-1],data]).transpose()
data_df

0  1
0  9  0
1  8  1
2  7  2
3  6  3
4  5  4
5  4  5
6  3  6
7  2  7
8  1  8
9  0  9

In [ ]:
index_row(data_df,7)

0    2
1    7
Name: 7, dtype: int64

In [ ]:
show_doc(listify)

<h4 id="listify" class="doc_header"><code>listify</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L129" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#listify-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>listify</code>(**`p`**:`OptListOrItem`=***`None`***, **`q`**:`OptListOrItem`=***`None`***)

<div class="collapse" id="listify-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#listify-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>listify</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_listify</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L25" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Make `p` listy and the same length as `q`.  

In [ ]:
to_match = np.arange(12)
listify('a',to_match)

['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a']

In [ ]:
listify('a',5)

['a', 'a', 'a', 'a', 'a']

In [ ]:
listify(77.1,3)

[77.1, 77.1, 77.1]

In [ ]:
listify( (1,2,3) )

[1, 2, 3]

In [ ]:
listify((1,2,3),('a','b','c'))

[1, 2, 3]

In [ ]:
show_doc(random_split)

<h4 id="random_split" class="doc_header"><code>random_split</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L123" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#random_split-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>random_split</code>(**`valid_pct`**:`float`, **\*`arrs`**:`NPArrayableList`) → `SplitArrayList`

<div class="collapse" id="random_split-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#random_split-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>random_split</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_random_split</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L154" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Randomly split `arrs` with `valid_pct` ratio. good for creating validation set.  

Splitting is done here with `random.uniform()` so you may not get the exact split percentage for small data sets

In [ ]:
data = np.arange(20).reshape(10,2)
data.tolist()

[[0, 1],
 [2, 3],
 [4, 5],
 [6, 7],
 [8, 9],
 [10, 11],
 [12, 13],
 [14, 15],
 [16, 17],
 [18, 19]]

In [ ]:
random_split(0.20,data.tolist())

[(array([[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]]),), (array([], shape=(0, 2), dtype=int64),)]

In [ ]:
random_split(0.20,pd.DataFrame(data))

[(array([[ 0,  1],
         [ 4,  5],
         [ 8,  9],
         [10, 11],
         [16, 17],
         [18, 19]]),), (array([[ 2,  3],
         [ 6,  7],
         [12, 13],
         [14, 15]]),)]

In [ ]:
show_doc(range_of)

<h4 id="range_of" class="doc_header"><code>range_of</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L229" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#range_of-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>range_of</code>(**`x`**)

<div class="collapse" id="range_of-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#range_of-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>range_of</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

Create a range from 0 to `len(x)`.  

In [ ]:
range_of([5,4,3])

[0, 1, 2]

In [ ]:
range_of(np.arange(10)[::-1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
show_doc(series2cat)

<h4 id="series2cat" class="doc_header"><code>series2cat</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L173" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#series2cat-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>series2cat</code>(**`df`**:`DataFrame`, **\*`col_names`**)

<div class="collapse" id="series2cat-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#series2cat-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>series2cat</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_series2cat</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L184" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Categorifies the columns `col_names` in `df`.  

In [ ]:
data_df = pd.DataFrame.from_dict({"a":[1,1,1,2,2,2],"b":['f','e','f','g','g','g']})
data_df

a  b
0  1  f
1  1  e
2  1  f
3  2  g
4  2  g
5  2  g

In [ ]:
data_df['b']

0    f
1    e
2    f
3    g
4    g
5    g
Name: b, dtype: object

In [ ]:
series2cat(data_df,'b')
data_df['b']

0    f
1    e
2    f
3    g
4    g
5    g
Name: b, dtype: category
Categories (3, object): [e < f < g]

In [ ]:
series2cat(data_df,'a')
data_df['a']

0    1
1    1
2    1
3    2
4    2
5    2
Name: a, dtype: category
Categories (2, int64): [1 < 2]

In [ ]:
show_doc(split_kwargs_by_func)

<h4 id="split_kwargs_by_func" class="doc_header"><code>split_kwargs_by_func</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L287" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#split_kwargs_by_func-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>split_kwargs_by_func</code>(**`kwargs`**, **`func`**)

<div class="collapse" id="split_kwargs_by_func-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#split_kwargs_by_func-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>split_kwargs_by_func</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

Split `kwargs` between those expected by `func` and the others.  

In [ ]:
key_word_args = {'url':'http://fast.ai','dest':'./','new_var':[1,2,3],'testvalue':42}
split_kwargs_by_func(key_word_args,download_url)

({'url': 'http://fast.ai', 'dest': './'},
 {'new_var': [1, 2, 3], 'testvalue': 42})

In [ ]:
show_doc(to_int)

<h4 id="to_int" class="doc_header"><code>to_int</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L88" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#to_int-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>to_int</code>(**`b`**:`Any`) → `Union`\[`int`, `List`\[`int`\]\]

<div class="collapse" id="to_int-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#to_int-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>to_int</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_to_int</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L86" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Recursively convert `b` to an int or list/dict of ints; raises exception if not convertible.  

In [ ]:
to_int(3.1415)

3

In [ ]:
data = [1.2,3.4,7.25]
to_int(data)

[1, 3, 7]

In [ ]:
show_doc(uniqueify)

<h4 id="uniqueify" class="doc_header"><code>uniqueify</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L100" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#uniqueify-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>uniqueify</code>(**`x`**:`Series`, **`sort`**:`bool`=***`False`***) → `List`\[`T`\]

<div class="collapse" id="uniqueify-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#uniqueify-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>uniqueify</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_uniqueify</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L53" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Return sorted unique values of `x`.  

In [ ]:
uniqueify( pd.Series(data=['a','a','b','b','f','g']) )

['a', 'b', 'f', 'g']

## Metaclasses

In [ ]:
show_doc(PrePostInitMeta)

<h2 id="PrePostInitMeta" class="doc_header"><code>class</code> <code>PrePostInitMeta</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L57" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#PrePostInitMeta-pytest" style="float:right; padding-right:10px">[test]</a></h2>

> <code>PrePostInitMeta</code>(**`name`**, **`bases`**, **`dct`**) :: `type`

<div class="collapse" id="PrePostInitMeta-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#PrePostInitMeta-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>PrePostInitMeta</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

A metaclass that calls optional `__pre_init__` and `__post_init__` methods  

In [ ]:
class _T(metaclass=PrePostInitMeta):
    def __pre_init__(self):  self.a  = 0; assert self.a==0
    def __init__(self):      self.a += 1; assert self.a==1
    def __post_init__(self): self.a += 1; assert self.a==2

t = _T()
t.a

2

## Files management and downloads

In [ ]:
show_doc(download_url)

<h4 id="download_url" class="doc_header"><code>download_url</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L196" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#download_url-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>download_url</code>(**`url`**:`str`, **`dest`**:`str`, **`overwrite`**:`bool`=***`False`***, **`pbar`**:`ProgressBar`=***`None`***, **`show_progress`**=***`True`***, **`chunk_size`**=***`1048576`***, **`timeout`**=***`4`***, **`retries`**=***`5`***)

<div class="collapse" id="download_url-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#download_url-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>download_url</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_download_url</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L193" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Download `url` to `dest` unless it exists and not `overwrite`.  

In [ ]:
show_doc(find_classes)

<h4 id="find_classes" class="doc_header"><code>find_classes</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L110" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#find_classes-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>find_classes</code>(**`folder`**:`Path`) → `FilePathList`

<div class="collapse" id="find_classes-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#find_classes-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>find_classes</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_find_classes</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L131" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

List of label subdirectories in imagenet-style `folder`.  

In [ ]:
show_doc(join_path)

<h4 id="join_path" class="doc_header"><code>join_path</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L238" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#join_path-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>join_path</code>(**`fname`**:`PathOrStr`, **`path`**:`PathOrStr`=***`'.'`***) → `Path`

<div class="collapse" id="join_path-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#join_path-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>join_path</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_join_paths</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L206" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Return `Path(path)/Path(fname)`, `path` defaults to current dir.  

In [ ]:
show_doc(join_paths)

<h4 id="join_paths" class="doc_header"><code>join_paths</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L242" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#join_paths-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>join_paths</code>(**`fnames`**:`FilePathList`, **`path`**:`PathOrStr`=***`'.'`***) → `FilePathList`

<div class="collapse" id="join_paths-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#join_paths-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>join_paths</code>:</p><p>Some other tests where <code>join_paths</code> is used:</p><ul><li><code>pytest -sv tests/test_core.py::test_join_paths</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L206" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Join `path` to every file name in `fnames`.  

In [ ]:
show_doc(loadtxt_str)

<h4 id="loadtxt_str" class="doc_header"><code>loadtxt_str</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L247" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#loadtxt_str-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>loadtxt_str</code>(**`path`**:`PathOrStr`) → `ndarray`

<div class="collapse" id="loadtxt_str-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#loadtxt_str-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>loadtxt_str</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

Return `ndarray` of `str` of lines of text from `path`.  

In [ ]:
show_doc(save_texts)

<h4 id="save_texts" class="doc_header"><code>save_texts</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L252" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#save_texts-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>save_texts</code>(**`fname`**:`PathOrStr`, **`texts`**:`StrList`)

<div class="collapse" id="save_texts-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#save_texts-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>save_texts</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

Save in `fname` the content of `texts`.  

## Multiprocessing

In [ ]:
show_doc(num_cpus)

<h4 id="num_cpus" class="doc_header"><code>num_cpus</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L43" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#num_cpus-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>num_cpus</code>() → `int`

<div class="collapse" id="num_cpus-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#num_cpus-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>num_cpus</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_cpus</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L8" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Get number of cpus  

In [ ]:
show_doc(parallel)

<h4 id="parallel" class="doc_header"><code>parallel</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L346" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#parallel-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>parallel</code>(**`func`**, **`arr`**:`Collection`\[`T_co`\], **`max_workers`**:`int`=***`None`***, **`leave`**=***`False`***)

<div class="collapse" id="parallel-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#parallel-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>parallel</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

Call `func` on every element of `arr` in parallel using `max_workers`.  

`func` must accept both the value and index of each `arr` element.

In [ ]:
def my_func(value, index):
    print("Index: {}, Value: {}".format(index, value))
 
my_array = [i*2 for i in range(5)]
parallel(my_func, my_array, max_workers=3)

Index: 0, Value: 0
Index: 1, Value: 2
Index: 2, Value: 4
Index: 4, Value: 8
Index: 3, Value: 6


In [ ]:
show_doc(partition)

<h4 id="partition" class="doc_header"><code>partition</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L165" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#partition-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>partition</code>(**`a`**:`Collection`\[`T_co`\], **`sz`**:`int`) → `List`\[`Collection`\[`T_co`\]\]

<div class="collapse" id="partition-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#partition-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>partition</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_partition_functionality</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L94" class="source_link" style="float:right">[source]</a></li></ul><p>Some other tests where <code>partition</code> is used:</p><ul><li><code>pytest -sv tests/test_core.py::test_partition</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L97" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Split iterables `a` in equal parts of size `sz`  

In [ ]:
show_doc(partition_by_cores)

<h4 id="partition_by_cores" class="doc_header"><code>partition_by_cores</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L169" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#partition_by_cores-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>partition_by_cores</code>(**`a`**:`Collection`\[`T_co`\], **`n_cpus`**:`int`) → `List`\[`Collection`\[`T_co`\]\]

<div class="collapse" id="partition_by_cores-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#partition_by_cores-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>partition_by_cores</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

Split data in `a` equally among `n_cpus` cores  

## Data block API

In [ ]:
show_doc(ItemBase, title_level=3)

<h3 id="ItemBase" class="doc_header"><code>class</code> <code>ItemBase</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L179" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#ItemBase-pytest" style="float:right; padding-right:10px">[test]</a></h3>

> <code>ItemBase</code>(**`data`**:`Any`)

<div class="collapse" id="ItemBase-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#ItemBase-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>ItemBase</code>:</p><p>Some other tests where <code>ItemBase</code> is used:</p><ul><li><code>pytest -sv tests/test_core.py::test_itembase_eq</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L242" class="source_link" style="float:right">[source]</a></li><li><code>pytest -sv tests/test_core.py::test_itembase_hash</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L304" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Base item type in the fastai library.  

All items used in fastai should subclass this. Must have a [`data`](/tabular.data.html#tabular.data) field that will be used when collating in mini-batches.

In [ ]:
show_doc(ItemBase.apply_tfms)

<h4 id="ItemBase.apply_tfms" class="doc_header"><code>apply_tfms</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L186" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#ItemBase-apply_tfms-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>apply_tfms</code>(**`tfms`**:`Collection`\[`T_co`\], **\*\*`kwargs`**)

<div class="collapse" id="ItemBase-apply_tfms-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#ItemBase-apply_tfms-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>apply_tfms</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

Subclass this method if you want to apply data augmentation with `tfms` to this [`ItemBase`](/core.html#ItemBase).  

In [ ]:
show_doc(ItemBase.show)

<h4 id="ItemBase.show" class="doc_header"><code>show</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L183" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#ItemBase-show-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>show</code>(**`ax`**:`Axes`, **\*\*`kwargs`**)

<div class="collapse" id="ItemBase-show-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#ItemBase-show-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>show</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

Subclass this method if you want to customize the way this [`ItemBase`](/core.html#ItemBase) is shown on `ax`.  

The default behavior is to set the string representation of this object as title of `ax`.

In [ ]:
show_doc(Category, title_level=3)

<h3 id="Category" class="doc_header"><code>class</code> <code>Category</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L307" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#Category-pytest" style="float:right; padding-right:10px">[test]</a></h3>

> <code>Category</code>(**`data`**, **`obj`**) :: [`ItemBase`](/core.html#ItemBase)

<div class="collapse" id="Category-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#Category-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>Category</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_itembase_eq</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L242" class="source_link" style="float:right">[source]</a></li></ul><p>Some other tests where <code>Category</code> is used:</p><ul><li><code>pytest -sv tests/test_core.py::test_itembase_hash</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L304" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Basic class for single classification labels.  

Create a [`Category`](/core.html#Category) with an `obj` of index [`data`](/tabular.data.html#tabular.data) in a certain classes list. 

In [ ]:
show_doc(EmptyLabel, title_level=3)

<h3 id="EmptyLabel" class="doc_header"><code>class</code> <code>EmptyLabel</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L301" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#EmptyLabel-pytest" style="float:right; padding-right:10px">[test]</a></h3>

> <code>EmptyLabel</code>() :: [`ItemBase`](/core.html#ItemBase)

<div class="collapse" id="EmptyLabel-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#EmptyLabel-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>EmptyLabel</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

Should be used for a dummy label.  

In [ ]:
show_doc(MultiCategory, title_level=3)

<h3 id="MultiCategory" class="doc_header"><code>class</code> <code>MultiCategory</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L314" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#MultiCategory-pytest" style="float:right; padding-right:10px">[test]</a></h3>

> <code>MultiCategory</code>(**`data`**, **`obj`**, **`raw`**) :: [`ItemBase`](/core.html#ItemBase)

<div class="collapse" id="MultiCategory-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#MultiCategory-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>MultiCategory</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_itembase_eq</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L242" class="source_link" style="float:right">[source]</a></li></ul><p>Some other tests where <code>MultiCategory</code> is used:</p><ul><li><code>pytest -sv tests/test_core.py::test_itembase_hash</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L304" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Basic class for multi-classification labels.  

Create a [`MultiCategory`](/core.html#MultiCategory) with an `obj` that is a collection of labels. [`data`](/tabular.data.html#tabular.data) corresponds to the one-hot encoded labels and `raw` is a list of associated string.

In [ ]:
show_doc(FloatItem)

<h2 id="FloatItem" class="doc_header"><code>class</code> <code>FloatItem</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L320" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#FloatItem-pytest" style="float:right; padding-right:10px">[test]</a></h2>

> <code>FloatItem</code>(**`obj`**) :: [`ItemBase`](/core.html#ItemBase)

<div class="collapse" id="FloatItem-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#FloatItem-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>FloatItem</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_itembase_eq</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L242" class="source_link" style="float:right">[source]</a></li></ul><p>Some other tests where <code>FloatItem</code> is used:</p><ul><li><code>pytest -sv tests/test_core.py::test_itembase_hash</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L304" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Basic class for float items.  

## Others

In [ ]:
show_doc(camel2snake)

<h4 id="camel2snake" class="doc_header"><code>camel2snake</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L145" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#camel2snake-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>camel2snake</code>(**`name`**:`str`) → `str`

<div class="collapse" id="camel2snake-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#camel2snake-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>camel2snake</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_camel2snake</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L164" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Change `name` from camel to snake style.  

In [ ]:
camel2snake('DeviceDataLoader')

'device_data_loader'

In [ ]:
show_doc(even_mults)

<h4 id="even_mults" class="doc_header"><code>even_mults</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L150" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#even_mults-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>even_mults</code>(**`start`**:`float`, **`stop`**:`float`, **`n`**:`int`) → `ndarray`

<div class="collapse" id="even_mults-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#even_mults-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>even_mults</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_even_mults</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L178" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Build log-stepped array from `start` to `stop` in `n` steps.  

In linear scales each element is equidistant from its neighbors:

In [ ]:
# from 1 to 10 in 5 steps
t = np.linspace(1, 10, 5)
t

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
for i in range(len(t) - 1):
    print(t[i+1] - t[i])

2.25
2.25
2.25
2.25


In logarithmic scales, each element is a multiple of the previous entry:

In [ ]:
t = even_mults(1, 10, 5)
t

array([ 1.      ,  1.778279,  3.162278,  5.623413, 10.      ])

In [ ]:
# notice how each number is a multiple of its predecessor
for i in range(len(t) - 1):
    print(t[i+1] / t[i])

1.7782794100389228
1.7782794100389228
1.7782794100389228
1.7782794100389228


In [ ]:
show_doc(func_args)

<h4 id="func_args" class="doc_header"><code>func_args</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L278" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#func_args-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>func_args</code>(**`func`**) → `bool`

<div class="collapse" id="func_args-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#func_args-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>func_args</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

Return the arguments of `func`.  

In [ ]:
func_args(download_url)

('url',
 'dest',
 'overwrite',
 'pbar',
 'show_progress',
 'chunk_size',
 'timeout',
 'retries')

Additionally, [`func_args`](/core.html#func_args) can be used with functions that do not belong to the fastai library

In [ ]:
func_args(np.linspace)

('start', 'stop', 'num', 'endpoint', 'retstep', 'dtype')

In [ ]:
show_doc(noop)

<h4 id="noop" class="doc_header"><code>noop</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L55" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#noop-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>noop</code>(**`x`**)

<div class="collapse" id="noop-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#noop-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>noop</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_noop</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L82" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Return `x`.

In [ ]:
# object is returned as-is
noop([1,2,3])

[1, 2, 3]

In [ ]:
show_doc(one_hot)

<h4 id="one_hot" class="doc_header"><code>one_hot</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L263" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#one_hot-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>one_hot</code>(**`x`**:`Collection`\[`int`\], **`c`**:`int`)

<div class="collapse" id="one_hot-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#one_hot-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>one_hot</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_one_hot</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L218" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

One-hot encode `x` with `c` classes.  

One-hot encoding is a standard machine learning technique. Assume we are dealing with a 10-class classification problem and we are supplied a list of labels:

In [ ]:
y = [1, 4, 4, 5, 7, 9, 2, 4, 0]

In [ ]:
jekyll_note("""y is zero-indexed, therefore its first element (1) belongs to class 2, its second element (4) to class 5 and so on.""")

<div markdown="span" class="alert alert-info" role="alert"><i class="fa fa-info-circle"></i> <b>Note: </b>y is zero-indexed, therefore its first element (1) belongs to class 2, its second element (4) to class 5 and so on.</div>

In [ ]:
len(y)

9

y can equivalently be expressed as a matrix of 9 rows and 10 columns, where each row represents one element of the original y. 

In [ ]:
for label in y:
    print(one_hot(label, 10))

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
show_doc(show_some)

<h4 id="show_some" class="doc_header"><code>show_some</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L367" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#show_some-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>show_some</code>(**`items`**:`Collection`\[`T_co`\], **`n_max`**:`int`=***`5`***, **`sep`**:`str`=***`','`***)

<div class="collapse" id="show_some-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#show_some-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>show_some</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

Return the representation of the first  `n_max` elements in `items`.  

In [ ]:
# select 3 elements from a list
some_data = show_some([10, 20, 30, 40, 50], 3) 
some_data

'10,20,30...'

In [ ]:
type(some_data) 

str

In [ ]:
# the separator can be changed
some_data = show_some([10, 20, 30, 40, 50], 3, sep = '---') 
some_data

'10---20---30...'

In [ ]:
some_data[:-3]

'10---20---30'

[`show_some`](/core.html#show_some) can take as input any class with \_\_len\_\_ and \_\_getitem\_\_ 

In [ ]:
class Any(object):
    def __init__(self, data):
        self.data = data
    def __len__(self):
        return len(self.data)
    def __getitem__(self,i):
        return self.data[i]
 
some_other_data = Any('nice')
show_some(some_other_data, 2)

'n,i...'

In [ ]:
show_doc(subplots)

<h4 id="subplots" class="doc_header"><code>subplots</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L358" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#subplots-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>subplots</code>(**`rows`**:`int`, **`cols`**:`int`, **`imgsize`**:`int`=***`4`***, **`figsize`**:`Optional`\[`Tuple`\[`int`, `int`\]\]=***`None`***, **`title`**=***`None`***, **\*\*`kwargs`**)

<div class="collapse" id="subplots-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#subplots-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>subplots</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_subplots_multi_row_cols</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L222" class="source_link" style="float:right">[source]</a></li><li><code>pytest -sv tests/test_core.py::test_subplots_single</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L229" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>

Like `plt.subplots` but with consistent axs shape, `kwargs` passed to `fig.suptitle` with `title`  

In [ ]:
show_doc(text2html_table)

<h4 id="text2html_table" class="doc_header"><code>text2html_table</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L332" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#text2html_table-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>text2html_table</code>(**`items`**:`Tokens`) → `str`

<div class="collapse" id="text2html_table-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#text2html_table-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>No tests found for <code>text2html_table</code>. To contribute a test please refer to <a href="/dev/test.html">this guide</a> and <a href="https://forums.fast.ai/t/improving-expanding-functional-tests/32929">this discussion</a>.</p></div></div>

Put the texts in `items` in an HTML table, `widths` are the widths of the columns in %.  

## Undocumented Methods - Methods moved below this line will intentionally be hidden

## New Methods - Please document or move to the undocumented section

In [ ]:
show_doc(is_dict)

<h4 id="is_dict" class="doc_header"><code>is_dict</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L53" class="source_link" style="float:right">[source]</a><a class="source_link" data-toggle="collapse" data-target="#is_dict-pytest" style="float:right; padding-right:10px">[test]</a></h4>

> <code>is_dict</code>(**`x`**:`Any`) → `bool`

<div class="collapse" id="is_dict-pytest"><div class="card card-body pytest_card"><a type="button" data-toggle="collapse" data-target="#is_dict-pytest" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a><p>Tests found for <code>is_dict</code>:</p><ul><li><code>pytest -sv tests/test_core.py::test_dict</code> <a href="https://github.com/fastai/fastai/blob/master/tests/test_core.py#L76" class="source_link" style="float:right">[source]</a></li></ul><p>To run tests please refer to this <a href="/dev/test.html#quick-guide">guide</a>.</p></div></div>