# Basic core

This module contains all the basic functions we need in other modules of the fastai library (split with [`torch_core`](/torch_core.html#torch_core) that contains the ones requiring pytorch). Its documentation can easily be skipped at a first read, unless you want to know what a given function does.

In [ ]:
from fastai.gen_doc.nbdoc import *
from fastai.core import * 

## Global constants

`default_cpus = min(16, num_cpus())` <div style="text-align: right"><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L45">[source]</a></div>

## Check functions

In [ ]:
show_doc(has_arg)

<h4 id="has_arg"><code>has_arg</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L246" class="source_link">[source]</a></h4>

> <code>has_arg</code>(<b>`func`</b>, <b>`arg`</b>) → `bool`

Check if `func` accepts `arg`.  

Examples for two [`fastai.core`](/core.html#core) functions.  Docstring shown before calling [`has_arg`](/core.html#has_arg) for reference


In [ ]:
has_arg(download_url,'url')

True

In [ ]:
has_arg(index_row,'x')

False

In [ ]:
has_arg(index_row,'a')

True

In [ ]:
show_doc(ifnone)

<h4 id="ifnone"><code>ifnone</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L64" class="source_link">[source]</a></h4>

> <code>ifnone</code>(<b>`a`</b>:`Any`, <b>`b`</b>:`Any`) → `Any`

`a` if `a` is not None, otherwise `b`.  

In [ ]:
param,alt_param = None,5
ifnone(param,alt_param)

5

In [ ]:
param,alt_param = None,[1,2,3]
ifnone(param,alt_param)

[1, 2, 3]

In [ ]:
show_doc(is1d)

<h4 id="is1d"><code>is1d</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L68" class="source_link">[source]</a></h4>

> <code>is1d</code>(<b>`a`</b>:`Collection`\[`T_co`\]) → `bool`

Return `True` if `a` is one-dimensional  

In [ ]:
two_d_array = np.arange(12).reshape(6,2)
print( two_d_array )
print( is1d(two_d_array) )

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
False


In [ ]:
is1d(two_d_array.flatten())

True

In [ ]:
show_doc(is_listy)

<h4 id="is_listy"><code>is_listy</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L51" class="source_link">[source]</a></h4>

> <code>is_listy</code>(<b>`x`</b>:`Any`) → `bool`

Check if `x` is a `Collection`. `Tuple` or `List` qualify

In [ ]:
some_data = [1,2,3]
is_listy(some_data)

True

In [ ]:
some_data = (1,2,3)
is_listy(some_data)

True

In [ ]:
some_data = 1024
print( is_listy(some_data) )

False


In [ ]:
print( is_listy( [some_data] ) )

True


In [ ]:
some_data = dict([('a',1),('b',2),('c',3)])
print( some_data )
print( some_data.keys() )

{'a': 1, 'b': 2, 'c': 3}
dict_keys(['a', 'b', 'c'])


In [ ]:
print( is_listy(some_data) )
print( is_listy(some_data.keys()) )

False
False


In [ ]:
print( is_listy(list(some_data.keys())) )

True


In [ ]:
show_doc(is_tuple)

<h4 id="is_tuple"><code>is_tuple</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L52" class="source_link">[source]</a></h4>

> <code>is_tuple</code>(<b>`x`</b>:`Any`) → `bool`

Check if `x` is a `tuple`.

In [ ]:
print( is_tuple( [1,2,3] ) )

False


In [ ]:
print( is_tuple( (1,2,3) ) )

True


## Collection related functions

In [ ]:
show_doc(arange_of)

<h4 id="arange_of"><code>arange_of</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L195" class="source_link">[source]</a></h4>

> <code>arange_of</code>(<b>`x`</b>)

Same as [`range_of`](/core.html#range_of) but returns an array.  

In [ ]:
arange_of([5,6,7])

array([0, 1, 2])

In [ ]:
type(arange_of([5,6,7]))

numpy.ndarray

In [ ]:
show_doc(array)

<h4 id="array"><code>array</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L256" class="source_link">[source]</a></h4>

> <code>array</code>(<b>`a`</b>, <b>`dtype`</b>:`type`=<b><i>`None`</i></b>, <b>`kwargs`</b>) → `ndarray`

Same as `np.array` but also handles generators  

In [ ]:
array([1,2,3])

array([1, 2, 3])

Note that after we call the generator, we do not reset.  So the [`array`](/core.html#array) call has 5 less entries than it would if we ran from the start of the generator.

In [ ]:
def data_gen():
    i = 100.01
    while i<200:
        yield i
        i += 1.

ex_data_gen = data_gen()
for _ in range(5):
    print(next(ex_data_gen))

100.01
101.01
102.01
103.01
104.01


In [ ]:
array(ex_data_gen)

array([105.01, 106.01, 107.01, 108.01, ..., 196.01, 197.01, 198.01, 199.01])

In [ ]:
ex_data_gen_int = data_gen()

array(ex_data_gen_int,dtype=int)  #Cast output to int array

array([100, 101, 102, 103, ..., 196, 197, 198, 199])

In [ ]:
show_doc(arrays_split)

<h4 id="arrays_split"><code>arrays_split</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L89" class="source_link">[source]</a></h4>

> <code>arrays_split</code>(<b>`mask`</b>:`ndarray`, <b>`arrs`</b>:`NPArrayableList`) → `SplitArrayList`

Given `arrs` is [a,b,...] and `mask`index - return[(a[mask],a[~mask]),(b[mask],b[~mask]),...].  

In [ ]:
data_a = np.arange(15)
data_b = np.arange(15)[::-1]

mask_a = (data_a > 10)
print(data_a)
print(data_b)
print(mask_a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[False False False False False False False False False False False  True  True  True  True]


In [ ]:
arrays_split(mask_a,data_a)

[(array([11, 12, 13, 14]),),
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),)]

In [ ]:
np.vstack([data_a,data_b]).transpose().shape

(15, 2)

In [ ]:
arrays_split(mask_a,np.vstack([data_a,data_b]).transpose()) #must match on dimension 0

[(array([[11,  3],
         [12,  2],
         [13,  1],
         [14,  0]]),), (array([[ 0, 14],
         [ 1, 13],
         [ 2, 12],
         [ 3, 11],
         [ 4, 10],
         [ 5,  9],
         [ 6,  8],
         [ 7,  7],
         [ 8,  6],
         [ 9,  5],
         [10,  4]]),)]

In [ ]:
show_doc(chunks)

<h4 id="chunks"><code>chunks</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L55" class="source_link">[source]</a></h4>

> <code>chunks</code>(<b>`l`</b>:`Collection`\[`T_co`\], <b>`n`</b>:`int`) → `Iterable`

Yield successive `n`-sized chunks from `l`.  

You can transform a `Collection` into an `Iterable` of 'n' sized chunks by calling [`chunks`](/core.html#chunks):

In [ ]:
data = [0,1,2,3,4,5,6,7,8,9]
for chunk in chunks(data, 2):
    print(chunk)

[0, 1]
[2, 3]
[4, 5]
[6, 7]
[8, 9]


In [ ]:
for chunk in chunks(data, 3):
    print(chunk)

[0, 1, 2]
[3, 4, 5]
[6, 7, 8]
[9]


In [ ]:
show_doc(df_names_to_idx)

<h4 id="df_names_to_idx"><code>df_names_to_idx</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L220" class="source_link">[source]</a></h4>

> <code>df_names_to_idx</code>(<b>`names`</b>:`IntsOrStrs`, <b>`df`</b>:`DataFrame`)

Return the column indexes of `names` in `df`.  

In [ ]:
ex_df = pd.DataFrame.from_dict({"a":[1,1,1],"b":[2,2,2]})
print(ex_df)

   a  b
0  1  2
1  1  2
2  1  2


In [ ]:
df_names_to_idx('b',ex_df)

[1]

In [ ]:
show_doc(extract_kwargs)

<h4 id="extract_kwargs"><code>extract_kwargs</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L124" class="source_link">[source]</a></h4>

> <code>extract_kwargs</code>(<b>`names`</b>:`StrList`, <b>`kwargs`</b>:`KWArgs`)

Extract the keys in `names` from the `kwargs`.  

In [ ]:
key_word_args = {"a":2,"some_list":[1,2,3],"param":'mean'}
key_word_args

{'a': 2, 'some_list': [1, 2, 3], 'param': 'mean'}

In [ ]:
(extracted_val,remainder) = extract_kwargs(['param'],key_word_args)
print( extracted_val,remainder )

{'param': 'mean'} {'a': 2, 'some_list': [1, 2, 3]}


In [ ]:
show_doc(idx_dict)

<h4 id="idx_dict"><code>idx_dict</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L78" class="source_link">[source]</a></h4>

> <code>idx_dict</code>(<b>`a`</b>)

Create a dictionary value to index from `a`.  

In [ ]:
idx_dict(['a','b','c'])

{'a': 0, 'b': 1, 'c': 2}

In [ ]:
show_doc(index_row)

<h4 id="index_row"><code>index_row</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L232" class="source_link">[source]</a></h4>

> <code>index_row</code>(<b>`a`</b>:`Union`\[`Collection`\[`T_co`\], `DataFrame`, `Series`\], <b>`idxs`</b>:`Collection`\[`int`\]) → `Any`

Return the slice of `a` corresponding to `idxs`.  

In [ ]:
data = [0,1,2,3,4,5,6,7,8,9]
index_row(data,4)

4

In [ ]:
index_row(pd.Series(data),7)

7

In [ ]:
data_df = pd.DataFrame([data[::-1],data]).transpose()
data_df

0  1
0  9  0
1  8  1
2  7  2
3  6  3
4  5  4
5  4  5
6  3  6
7  2  7
8  1  8
9  0  9

In [ ]:
index_row(data_df,7)

0    2
1    7
Name: 7, dtype: int64

In [ ]:
show_doc(listify)

<h4 id="listify"><code>listify</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L101" class="source_link">[source]</a></h4>

> <code>listify</code>(<b>`p`</b>:`OptListOrItem`=<b><i>`None`</i></b>, <b>`q`</b>:`OptListOrItem`=<b><i>`None`</i></b>)

Make `p` listy and the same length as `q`.  

In [ ]:
to_match = np.arange(12)
listify('a',to_match)

['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a']

In [ ]:
listify('a',5)

['a', 'a', 'a', 'a', 'a']

In [ ]:
listify(77.1,3)

[77.1, 77.1, 77.1]

In [ ]:
listify( (1,2,3) )

[1, 2, 3]

In [ ]:
listify((1,2,3),('a','b','c'))

[1, 2, 3]

In [ ]:
show_doc(random_split)

<h4 id="random_split"><code>random_split</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L95" class="source_link">[source]</a></h4>

> <code>random_split</code>(<b>`valid_pct`</b>:`float`, <b>`arrs`</b>:`NPArrayableList`) → `SplitArrayList`

Randomly split `arrs` with `valid_pct` ratio. good for creating validation set.  

Splitting is done here with `random.uniform()` so you may not get the exact split percentage for small data sets

In [ ]:
data = np.arange(20).reshape(10,2)
data.tolist()

[[0, 1],
 [2, 3],
 [4, 5],
 [6, 7],
 [8, 9],
 [10, 11],
 [12, 13],
 [14, 15],
 [16, 17],
 [18, 19]]

In [ ]:
random_split(0.20,data.tolist())

[(array([[ 0,  1],
         [ 2,  3],
         [ 6,  7],
         [ 8,  9],
         [10, 11],
         [16, 17],
         [18, 19]]),), (array([[ 4,  5],
         [12, 13],
         [14, 15]]),)]

In [ ]:
random_split(0.20,pd.DataFrame(data))

[(array([[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]]),), (array([], shape=(0, 2), dtype=int64),)]

In [ ]:
show_doc(range_of)

<h4 id="range_of"><code>range_of</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L192" class="source_link">[source]</a></h4>

> <code>range_of</code>(<b>`x`</b>)

Create a range from 0 to `len(x)`.  

In [ ]:
range_of([5,4,3])

[0, 1, 2]

In [ ]:
range_of(np.arange(10)[::-1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
show_doc(series2cat)

<h4 id="series2cat"><code>series2cat</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L141" class="source_link">[source]</a></h4>

> <code>series2cat</code>(<b>`df`</b>:`DataFrame`, <b>`col_names`</b>)

Categorifies the columns `col_names` in `df`.  

In [ ]:
data_df = pd.DataFrame.from_dict({"a":[1,1,1,2,2,2],"b":['f','e','f','g','g','g']})
data_df

a  b
0  1  f
1  1  e
2  1  f
3  2  g
4  2  g
5  2  g

In [ ]:
data_df['b']

0    f
1    e
2    f
3    g
4    g
5    g
Name: b, dtype: object

In [ ]:
series2cat(data_df,'b')
data_df['b']

0    f
1    e
2    f
3    g
4    g
5    g
Name: b, dtype: category
Categories (3, object): [e < f < g]

In [ ]:
series2cat(data_df,'a')
data_df['a']

0    1
1    1
2    1
3    2
4    2
5    2
Name: a, dtype: category
Categories (2, int64): [1 < 2]

In [ ]:
show_doc(split_kwargs_by_func)

<h4 id="split_kwargs_by_func"><code>split_kwargs_by_func</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L250" class="source_link">[source]</a></h4>

> <code>split_kwargs_by_func</code>(<b>`kwargs`</b>, <b>`func`</b>)

Split `kwargs` between those expected by `func` and the others.  

In [ ]:
key_word_args = {'url':'http://fast.ai','dest':'./','new_var':[1,2,3],'testvalue':42}
split_kwargs_by_func(key_word_args,download_url)

({'url': 'http://fast.ai', 'dest': './'},
 {'new_var': [1, 2, 3], 'testvalue': 42})

In [ ]:
show_doc(to_int)

<h4 id="to_int"><code>to_int</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L59" class="source_link">[source]</a></h4>

> <code>to_int</code>(<b>`b`</b>:`Any`) → `Union`\[`int`, `List`\[`int`\]\]

Convert `b` to an int or list of ints (if [`is_listy`](/core.html#is_listy)); raises exception if not convertible  

In [ ]:
to_int(3.1415)

3

In [ ]:
data = [1.2,3.4,7.25]
to_int(data)

[1, 3, 7]

In [ ]:
show_doc(uniqueify)

<h4 id="uniqueify"><code>uniqueify</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L72" class="source_link">[source]</a></h4>

> <code>uniqueify</code>(<b>`x`</b>:`Series`) → `List`\[`T`\]

Return sorted unique values of `x`.  

In [ ]:
uniqueify( pd.Series(data=['a','a','b','b','f','g']) )

['a', 'b', 'f', 'g']

## Files management and downloads

In [ ]:
show_doc(download_url)

<h4 id="download_url"><code>download_url</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L159" class="source_link">[source]</a></h4>

> <code>download_url</code>(<b>`url`</b>:`str`, <b>`dest`</b>:`str`, <b>`overwrite`</b>:`bool`=<b><i>`False`</i></b>, <b>`pbar`</b>:`ProgressBar`=<b><i>`None`</i></b>, <b>`show_progress`</b>=<b><i>`True`</i></b>, <b>`chunk_size`</b>=<b><i>`1048576`</i></b>, <b>`timeout`</b>=<b><i>`4`</i></b>, <b>`retries`</b>=<b><i>`5`</i></b>)

Download `url` to `dest` unless it exists and not `overwrite`.  

In [ ]:
show_doc(find_classes)

<h4 id="find_classes"><code>find_classes</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L82" class="source_link">[source]</a></h4>

> <code>find_classes</code>(<b>`folder`</b>:`Path`) → `FilePathList`

List of label subdirectories in imagenet-style `folder`.  

In [ ]:
show_doc(join_path)

<h4 id="join_path"><code>join_path</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L201" class="source_link">[source]</a></h4>

> <code>join_path</code>(<b>`fname`</b>:`PathOrStr`, <b>`path`</b>:`PathOrStr`=<b><i>`'.'`</i></b>) → `Path`

Return `Path(path)/Path(fname)`, `path` defaults to current dir.  

In [ ]:
show_doc(join_paths)

<h4 id="join_paths"><code>join_paths</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L205" class="source_link">[source]</a></h4>

> <code>join_paths</code>(<b>`fnames`</b>:`FilePathList`, <b>`path`</b>:`PathOrStr`=<b><i>`'.'`</i></b>) → `FilePathList`

Join `path` to every file name in `fnames`.  

In [ ]:
show_doc(loadtxt_str)

<h4 id="loadtxt_str"><code>loadtxt_str</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L210" class="source_link">[source]</a></h4>

> <code>loadtxt_str</code>(<b>`path`</b>:`PathOrStr`) → `ndarray`

Return `ndarray` of `str` of lines of text from `path`.  

In [ ]:
show_doc(save_texts)

<h4 id="save_texts"><code>save_texts</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L215" class="source_link">[source]</a></h4>

> <code>save_texts</code>(<b>`fname`</b>:`PathOrStr`, <b>`texts`</b>:`StrList`)

Save in `fname` the content of `texts`.  

## Multiprocessing

In [ ]:
show_doc(num_cpus)

<h4 id="num_cpus"><code>num_cpus</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L43" class="source_link">[source]</a></h4>

> <code>num_cpus</code>() → `int`

Get number of cpus  

In [ ]:
show_doc(parallel)

<h4 id="parallel"><code>parallel</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L298" class="source_link">[source]</a></h4>

> <code>parallel</code>(<b>`func`</b>, <b>`arr`</b>:`Collection`\[`T_co`\], <b>`max_workers`</b>:`int`=<b><i>`None`</i></b>)

Call `func` on every element of `arr` in parallel using `max_workers`.  

In [ ]:
show_doc(partition)

<h4 id="partition"><code>partition</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L133" class="source_link">[source]</a></h4>

> <code>partition</code>(<b>`a`</b>:`Collection`\[`T_co`\], <b>`sz`</b>:`int`) → `List`\[`Collection`\[`T_co`\]\]

Split iterables `a` in equal parts of size `sz`  

In [ ]:
show_doc(partition_by_cores)

<h4 id="partition_by_cores"><code>partition_by_cores</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L137" class="source_link">[source]</a></h4>

> <code>partition_by_cores</code>(<b>`a`</b>:`Collection`\[`T_co`\], <b>`n_cpus`</b>:`int`) → `List`\[`Collection`\[`T_co`\]\]

Split data in `a` equally among `n_cpus` cores  

## Data block API

In [ ]:
show_doc(ItemBase, title_level=3)

<h3 id="ItemBase"><code>class</code> <code>ItemBase</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L147" class="source_link">[source]</a></h3>

> <code>ItemBase</code>(<b>`data`</b>:`Any`)

Base item type in the fastai library.  

All items used in fastai should subclass this. Must have a [`data`](/tabular.data.html#tabular.data) field that will be used when collating in mini-batches.

In [ ]:
show_doc(ItemBase.apply_tfms)

<h4 id="ItemBase.apply_tfms"><code>apply_tfms</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L154" class="source_link">[source]</a></h4>

> <code>apply_tfms</code>(<b>`tfms`</b>:`Collection`\[`T_co`\], <b>`kwargs`</b>)

Subclass this method if you want to apply data augmentation with `tfms` to this [`ItemBase`](/core.html#ItemBase).  

In [ ]:
show_doc(ItemBase.show)

<h4 id="ItemBase.show"><code>show</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L151" class="source_link">[source]</a></h4>

> <code>show</code>(<b>`ax`</b>:`Axes`, <b>`kwargs`</b>)

Subclass this method if you want to customize the way this [`ItemBase`](/core.html#ItemBase) is shown on `ax`.  

The default behavior is to set the string representation of this object as title of `ax`.

In [ ]:
show_doc(Category, title_level=3)

<h3 id="Category"><code>class</code> <code>Category</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L269" class="source_link">[source]</a></h3>

> <code>Category</code>(<b>`data`</b>, <b>`obj`</b>) :: [`ItemBase`](/core.html#ItemBase)

Basic class for singe classification labels.  

Create a [`Category`](/core.html#Category) with an `obj` of index [`data`](/tabular.data.html#tabular.data) in a certain classes list. 

In [ ]:
show_doc(EmptyLabel, title_level=3)

<h3 id="EmptyLabel"><code>class</code> <code>EmptyLabel</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L264" class="source_link">[source]</a></h3>

> <code>EmptyLabel</code>() :: [`ItemBase`](/core.html#ItemBase)

Should be used for a dummy label.  

In [ ]:
show_doc(MultiCategory, title_level=3)

<h3 id="MultiCategory"><code>class</code> <code>MultiCategory</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L275" class="source_link">[source]</a></h3>

> <code>MultiCategory</code>(<b>`data`</b>, <b>`obj`</b>, <b>`raw`</b>) :: [`ItemBase`](/core.html#ItemBase)

Basic class for multi-classification labels.  

Create a [`MultiCategory`](/core.html#MultiCategory) with an `obj` that is a collection of labels. [`data`](/tabular.data.html#tabular.data) corresponds to the one-hot encoded labels and `raw` is a list of associated string.

In [ ]:
show_doc(FloatItem)

<h2 id="FloatItem"><code>class</code> <code>FloatItem</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L280" class="source_link">[source]</a></h2>

> <code>FloatItem</code>(<b>`obj`</b>) :: [`ItemBase`](/core.html#ItemBase)

Basic class for float items.  

## Others

In [ ]:
show_doc(camel2snake)

<h4 id="camel2snake"><code>camel2snake</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L113" class="source_link">[source]</a></h4>

> <code>camel2snake</code>(<b>`name`</b>:`str`) → `str`

Change `name` from camel to snake style.  

In [ ]:
camel2snake('DeviceDataLoader')

'device_data_loader'

In [ ]:
show_doc(even_mults)

<h4 id="even_mults"><code>even_mults</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L118" class="source_link">[source]</a></h4>

> <code>even_mults</code>(<b>`start`</b>:`float`, <b>`stop`</b>:`float`, <b>`n`</b>:`int`) → `ndarray`

Build log-stepped array from `start` to `stop` in `n` steps.  

In [ ]:
show_doc(func_args)

<h4 id="func_args"><code>func_args</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L241" class="source_link">[source]</a></h4>

> <code>func_args</code>(<b>`func`</b>) → `bool`

Return the arguments of `func`.  

In [ ]:
show_doc(noop)

<h4 id="noop"><code>noop</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L53" class="source_link">[source]</a></h4>

> <code>noop</code>(<b>`x`</b>)

Return `x`.

In [ ]:
show_doc(one_hot)

<h4 id="one_hot"><code>one_hot</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L226" class="source_link">[source]</a></h4>

> <code>one_hot</code>(<b>`x`</b>:`Collection`\[`int`\], <b>`c`</b>:`int`)

One-hot encode `x` with `c` classes.  

In [ ]:
show_doc(show_some)

<h4 id="show_some"><code>show_some</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L315" class="source_link">[source]</a></h4>

> <code>show_some</code>(<b>`items`</b>:`Collection`\[`T_co`\], <b>`n_max`</b>:`int`=<b><i>`5`</i></b>, <b>`sep`</b>:`str`=<b><i>`','`</i></b>)

Return the representation of the first  `n_max` elements in `items`.  

In [ ]:
show_doc(subplots)

<h4 id="subplots"><code>subplots</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L307" class="source_link">[source]</a></h4>

> <code>subplots</code>(<b>`rows`</b>:`int`, <b>`cols`</b>:`int`, <b>`imgsize`</b>:`int`=<b><i>`4`</i></b>, <b>`figsize`</b>:`Optional`\[`Tuple`\[`int`, `int`\]\]=<b><i>`None`</i></b>, <b>`title`</b>=<b><i>`None`</i></b>, <b>`kwargs`</b>)

Like `plt.subplots` but with consistent axs shape, `kwargs` passed to `fig.suptitle` with `title`  

In [ ]:
show_doc(text2html_table)

<h4 id="text2html_table"><code>text2html_table</code><a href="https://github.com/fastai/fastai/blob/master/fastai/core.py#L288" class="source_link">[source]</a></h4>

> <code>text2html_table</code>(<b>`items`</b>:`Tokens`, <b>`widths`</b>:`Collection`\[`int`\]) → `str`

Put the texts in `items` in an HTML table, `widths` are the widths of the columns in %.  

## Undocumented Methods - Methods moved below this line will intentionally be hidden

## New Methods - Please document or move to the undocumented section