# Torch Core

This module contains all the basic functions we need in other modules of the fastai library (split with [`core`](/core.html#core) that contains the ones not requiring pytorch). Its documentation can easily be skipped at a first read, unless you want to know what a given fuction does.

In [ ]:
from fastai.gen_doc.nbdoc import *
from fastai.torch_core import * 

## Global constants

`AdamW = partial(optim.Adam, betas=(0.9,0.99))` <div style="text-align: right"><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L43">[source]</a></div>

`bn_types = (nn.BatchNorm1d, nn.BatchNorm2d, nn.BatchNorm3d)` <div style="text-align: right"><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L41">[source]</a></div>

`defaults.device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')` <div style="text-align: right"><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L62">[source]</a></div>

If you are trying to make fastai run on the CPU, simply change the default device: `defaults.device = 'cpu'`. 

Alternatively, if not using wildcard imports: `fastai.torch_core.defaults.device = 'cpu'`.

## Functions that operate conversions

In [ ]:
show_doc(flatten_model, full_name='flatten')

<h4 id="flatten"><code>flatten</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L131" class="source_link">[source]</a></h4>

> <code>flatten</code>(<b>`m`</b>)

Flattens all the layers of `m`. 

In [ ]:
show_doc(model2half)

<h4 id="model2half"><code>model2half</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L186" class="source_link">[source]</a></h4>

> <code>model2half</code>(<b>`model`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module)) → [`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module)

Convert `model` to half precision except the batchnorm layers.  

In [ ]:
show_doc(np2model_tensor)

<h4 id="np2model_tensor"><code>np2model_tensor</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L233" class="source_link">[source]</a></h4>

> <code>np2model_tensor</code>(<b>`a`</b>)

Tranform numpy array `a` to a tensor of the same type.  

In [ ]:
show_doc(requires_grad)

<h4 id="requires_grad"><code>requires_grad</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L107" class="source_link">[source]</a></h4>

> <code>requires_grad</code>(<b>`m`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module), <b>`b`</b>:`Optional`\[`bool`\]=<b><i>`None`</i></b>) → `Optional`\[`bool`\]

If `b` is not set [`requires_grad`](/torch_core.html#requires_grad) on all params in `m`, else return [`requires_grad`](/torch_core.html#requires_grad) of first param.  

In [ ]:
show_doc(tensor)

<h4 id="tensor"><code>tensor</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L65" class="source_link">[source]</a></h4>

> <code>tensor</code>(<b>`x`</b>:`Any`, <b>`rest`</b>) → `Tensor`

Like `torch.as_tensor`, but handle lists too, and can pass multiple vector elements directly.  

In [ ]:
show_doc(to_cpu)

<h4 id="to_cpu"><code>to_cpu</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L92" class="source_link">[source]</a></h4>

> <code>to_cpu</code>(<b>`b`</b>:`ItemsList`)

Recursively map lists of tensors in `b ` to the cpu.  

In [ ]:
show_doc(to_data)

<h4 id="to_data"><code>to_data</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L87" class="source_link">[source]</a></h4>

> <code>to_data</code>(<b>`b`</b>:`ItemsList`)

Recursively map lists of items in `b ` to their wrapped data.  

In [ ]:
show_doc(to_detach)

<h4 id="to_detach"><code>to_detach</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L80" class="source_link">[source]</a></h4>

> <code>to_detach</code>(<b>`b`</b>:`Tensors`, <b>`cpu`</b>:`bool`=<b><i>`True`</i></b>)

Recursively detach lists of tensors in `b `; put them on the CPU if `cpu=True`.  

In [ ]:
show_doc(to_device)

<h4 id="to_device"><code>to_device</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L97" class="source_link">[source]</a></h4>

> <code>to_device</code>(<b>`b`</b>:`Tensors`, <b>`device`</b>:[`device`](https://pytorch.org/docs/stable/tensor_attributes.html#torch-device))

Recursively put `b` on `device`.  

In [ ]:
show_doc(to_half)

<h4 id="to_half"><code>to_half</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L176" class="source_link">[source]</a></h4>

> <code>to_half</code>(<b>`b`</b>:`Collection`\[`Tensor`\]) → `Collection`\[`Tensor`\]

Set the input of batch `b` to half precision if isn't an int type.  

In [ ]:
show_doc(to_np)

<h4 id="to_np"><code>to_np</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L251" class="source_link">[source]</a></h4>

> <code>to_np</code>(<b>`x`</b>)

Convert a tensor to a numpy array.  

In [ ]:
show_doc(try_int)

<h4 id="try_int"><code>try_int</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L305" class="source_link">[source]</a></h4>

> <code>try_int</code>(<b>`o`</b>:`Any`) → `Any`

Try to convert `o` to int, default to `o` if not possible.  

## Functions to deal with model initialization

In [ ]:
show_doc(apply_init)

<h4 id="apply_init"><code>apply_init</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L207" class="source_link">[source]</a></h4>

> <code>apply_init</code>(<b>`m`</b>, <b>`init_func`</b>:`LayerFunc`)

Initialize all non-batchnorm layers of `m` with `init_func`.  

In [ ]:
show_doc(apply_leaf)

<h4 id="apply_leaf"><code>apply_leaf</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L201" class="source_link">[source]</a></h4>

> <code>apply_leaf</code>(<b>`m`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module), <b>`f`</b>:`LayerFunc`)

Apply `f` to children of `m`.  

In [ ]:
show_doc(cond_init)

<h4 id="cond_init"><code>cond_init</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L197" class="source_link">[source]</a></h4>

> <code>cond_init</code>(<b>`m`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module), <b>`init_func`</b>:`LayerFunc`)

Initialize the non-batchnorm layers of `m` with `init_func`.  

In [ ]:
show_doc(in_channels)

<h4 id="in_channels"><code>in_channels</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L211" class="source_link">[source]</a></h4>

> <code>in_channels</code>(<b>`m`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module)) → `List`\[`int`\]

Return the shape of the first weight layer in `m`.  

In [ ]:
show_doc(init_default)

<h4 id="init_default"><code>init_default</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L190" class="source_link">[source]</a></h4>

> <code>init_default</code>(<b>`m`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module), <b>`func`</b>:`LayerFunc`=<b><i>`'kaiming_normal_'`</i></b>)

Initialize `m` weights with `func` and set `bias` to 0.  

## Functions to get information of a model

In [ ]:
show_doc(children)

<h4 id="children"><code>children</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L119" class="source_link">[source]</a></h4>

> <code>children</code>(<b>`m`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module)) → `ModuleList`

Get children of `m`.  

In [ ]:
show_doc(first_layer)

<h4 id="first_layer"><code>first_layer</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L132" class="source_link">[source]</a></h4>

> <code>first_layer</code>(<b>`m`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module)) → [`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module)

Retrieve first layer in a module `m`.  

In [ ]:
show_doc(last_layer)

<h4 id="last_layer"><code>last_layer</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L136" class="source_link">[source]</a></h4>

> <code>last_layer</code>(<b>`m`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module)) → [`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module)

Retrieve last layer in a module `m`.  

In [ ]:
show_doc(num_children)

<h4 id="num_children"><code>num_children</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L123" class="source_link">[source]</a></h4>

> <code>num_children</code>(<b>`m`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module)) → `int`

Get number of children modules in `m`.  

In [ ]:
show_doc(one_param)

<h4 id="one_param"><code>one_param</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L301" class="source_link">[source]</a></h4>

> <code>one_param</code>(<b>`m`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module)) → `Tensor`

Return the first parameter of `m`.  

In [ ]:
show_doc(range_children)

<h4 id="range_children"><code>range_children</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L127" class="source_link">[source]</a></h4>

> <code>range_children</code>(<b>`m`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module)) → `Iterator`\[`int`\]

Return iterator of len of children of `m`.  

In [ ]:
show_doc(trainable_params)

<h4 id="trainable_params"><code>trainable_params</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L114" class="source_link">[source]</a></h4>

> <code>trainable_params</code>(<b>`m`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module)) → `ParamList`

Return list of trainable params in `m`.  

## Functions to deal with BatchNorm layers

In [ ]:
show_doc(bn2float)

<h4 id="bn2float"><code>bn2float</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L180" class="source_link">[source]</a></h4>

> <code>bn2float</code>(<b>`module`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module)) → [`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module)

If `module` is batchnorm don't use half precision.  

In [ ]:
show_doc(set_bn_eval)

<h4 id="set_bn_eval"><code>set_bn_eval</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L169" class="source_link">[source]</a></h4>

> <code>set_bn_eval</code>(<b>`m`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module))

Set bn layers in eval mode for all recursive children of `m`.  

In [ ]:
show_doc(split_bn_bias)

<h4 id="split_bn_bias"><code>split_bn_bias</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L158" class="source_link">[source]</a></h4>

> <code>split_bn_bias</code>(<b>`layer_groups`</b>:`ModuleList`) → `ModuleList`

Split the layers in `layer_groups` into batchnorm (`bn_types`) and non-batchnorm groups.  

## Functions to get random tensors

In [ ]:
show_doc(log_uniform)

<h4 id="log_uniform"><code>log_uniform</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L288" class="source_link">[source]</a></h4>

> <code>log_uniform</code>(<b>`low`</b>, <b>`high`</b>, <b>`size`</b>:`Optional`\[`List`\[`int`\]\]=<b><i>`None`</i></b>) → `FloatOrTensor`

Draw 1 or shape=`size` random floats from uniform dist: min=log(`low`), max=log(`high`).  

In [ ]:
log_uniform(0.5,2,(8,))

tensor([0.5775, 0.7902, 0.6087, 0.5730, 0.8057, 0.8845, 0.8975, 0.5585])

In [ ]:
show_doc(rand_bool)

<h4 id="rand_bool"><code>rand_bool</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L293" class="source_link">[source]</a></h4>

> <code>rand_bool</code>(<b>`p`</b>:`float`, <b>`size`</b>:`Optional`\[`List`\[`int`\]\]=<b><i>`None`</i></b>) → `BoolOrTensor`

Draw 1 or shape=`size` random booleans (`True` occuring with probability `p`).  

In [ ]:
rand_bool(0.5, 8)

tensor([1, 1, 0, 1, 0, 0, 1, 0], dtype=torch.uint8)

In [ ]:
show_doc(uniform)

<h4 id="uniform"><code>uniform</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L283" class="source_link">[source]</a></h4>

> <code>uniform</code>(<b>`low`</b>:`Number`, <b>`high`</b>:`Number`=<b><i>`None`</i></b>, <b>`size`</b>:`Optional`\[`List`\[`int`\]\]=<b><i>`None`</i></b>) → `FloatOrTensor`

Draw 1 or shape=`size` random floats from uniform dist: min=`low`, max=`high`.  

In [ ]:
uniform(0,1,(8,))

tensor([0.6432, 0.3110, 0.7588, 0.7058, 0.7121, 0.8552, 0.3352, 0.2620])

In [ ]:
show_doc(uniform_int)

<h4 id="uniform_int"><code>uniform_int</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L297" class="source_link">[source]</a></h4>

> <code>uniform_int</code>(<b>`low`</b>:`int`, <b>`high`</b>:`int`, <b>`size`</b>:`Optional`\[`List`\[`int`\]\]=<b><i>`None`</i></b>) → `IntOrTensor`

Generate int or tensor `size` of ints between `low` and `high` (included).  

In [ ]:
uniform_int(0,2,(8,))

tensor([0, 1, 1, 2, 1, 1, 1, 2])

## Other functions

In [ ]:
show_doc(FloatItem, title_level=3)

<h3 id="FloatItem"><code>class</code> <code>FloatItem</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L263" class="source_link">[source]</a></h3>

> <code>FloatItem</code>(<b>`obj`</b>) :: [`ItemBase`](/core.html#ItemBase)

Basic class for float items.  

In [ ]:
show_doc(calc_loss)

<h4 id="calc_loss"><code>calc_loss</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L217" class="source_link">[source]</a></h4>

> <code>calc_loss</code>(<b>`y_pred`</b>:`Tensor`, <b>`y_true`</b>:`Tensor`, <b>`loss_func`</b>:`LossFunction`)

Calculate loss between `y_pred` and `y_true` using `loss_func`.  

In [ ]:
show_doc(data_collate)

<h4 id="data_collate"><code>data_collate</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L103" class="source_link">[source]</a></h4>

> <code>data_collate</code>(<b>`batch`</b>:`ItemsList`) → `Tensor`

Convert `batch` items to tensor data.  

In [ ]:
show_doc(grab_idx)

<h4 id="grab_idx"><code>grab_idx</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L268" class="source_link">[source]</a></h4>

> <code>grab_idx</code>(<b>`x`</b>, <b>`i`</b>, <b>`batch_first`</b>:`bool`=<b><i>`True`</i></b>)

Grab the `i`-th batch in `x`, `batch_first` stating the batch dimension.  

In [ ]:
show_doc(logit)

<h4 id="logit"><code>logit</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L273" class="source_link">[source]</a></h4>

> <code>logit</code>(<b>`x`</b>:`Tensor`) → `Tensor`

Logit of `x`, clamped to avoid inf.  

In [ ]:
show_doc(logit_)

<h4 id="logit_"><code>logit_</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L278" class="source_link">[source]</a></h4>

> <code>logit_</code>(<b>`x`</b>:`Tensor`) → `Tensor`

Inplace logit of `x`, clamped to avoid inf  

In [ ]:
show_doc(model_type)

<h4 id="model_type"><code>model_type</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L227" class="source_link">[source]</a></h4>

> <code>model_type</code>(<b>`dtype`</b>)

Return the torch type corresponding to `dtype`.  

In [ ]:
show_doc(np_address)

<h4 id="np_address"><code>np_address</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L76" class="source_link">[source]</a></h4>

> <code>np_address</code>(<b>`x`</b>:`ndarray`) → `int`

Address of `x` in memory.  

In [ ]:
show_doc(split_model)

<h4 id="split_model"><code>split_model</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L147" class="source_link">[source]</a></h4>

> <code>split_model</code>(<b>`model`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module), <b>`splits`</b>:`Collection`\[`Union`\[[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module), `ModuleList`\]\], <b>`want_idxs`</b>:`bool`=<b><i>`False`</i></b>)

Split `model` according to the layers in `splits`.  

If `splits` are layers, the model is split at those (not included) sequentially. If `want_idxs` is True, the corresponding indexes are returned. If `splits` are lists of layers, the model is split according to those.

In [ ]:
show_doc(split_model_idx)

<h4 id="split_model_idx"><code>split_model_idx</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L140" class="source_link">[source]</a></h4>

> <code>split_model_idx</code>(<b>`model`</b>:[`Module`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module), <b>`idxs`</b>:`Collection`\[`int`\]) → `ModuleList`

Split `model` according to the indexes in `idxs`.  

In [ ]:
show_doc(trange_of)

<h4 id="trange_of"><code>trange_of</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L247" class="source_link">[source]</a></h4>

> <code>trange_of</code>(<b>`x`</b>)

Create a tensor from `range_of(x)`.  

## Undocumented Methods - Methods moved below this line will intentionally be hidden

In [ ]:
show_doc(tensor__array__)

<h4 id="tensor__array__"><code>tensor__array__</code><a href="https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L256" class="source_link">[source]</a></h4>

> <code>tensor__array__</code>(<b>`dtype`</b>=<b><i>`None`</i></b>)

## New Methods - Please document or move to the undocumented section